ShoppingLists.Web/Controllers/ShoppingListsController.cs
using System.Web.Mvc;
using NLog;
using ShoppingLists.BusinessLayer;
using ShoppingLists.Shared;
using ShoppingLists.Shared.ServiceInterfaces;
using ShoppingLists.Web.Models;

namespace ShoppingLists.Web.Controllers
{
    [Authorize]
    public class ShoppingListsController : Controller
    {
        private static readonly Logger _log = LogManager.GetCurrentClassLogger();
        private IUserContext _userContext;
        private IShoppingListService _shoppingListService;
        private IUserService _userService;

        public ShoppingListsController(IUserContext userContext, IShoppingListService shoppingListService, IUserService userService)
        {
            _userContext = userContext;
            _shoppingListService = shoppingListService;
            _userService = userService;
        }

        public ActionResult Index()
        {
            var shoppingLists = _shoppingListService.FindAllForCurrentUser();
            return View(new ShoppingListsIndexModel(shoppingLists, _userContext.UserId));
        }

        public ActionResult Show(long id)
        {
            var shoppingList = _shoppingListService.Get(id, includeListItems: true);
            var currentUser = _userService.Get(_userContext.UserId, includePermissions: true, shoppingListId: id);
            return View(new ShoppingListModel(shoppingList, currentUser));
        }

        public ActionResult Share(long id)
        {
            var shoppingList = _shoppingListService.Get(id);
            var users = _userService.GetAllForShoppingList(id);
            var shoppingListSharingModel = new ShoppingListSharingModel(shoppingList, users, _userContext.UserId);
            return View(shoppingListSharingModel);
        }
    }
}

ShoppingLists.Web/Views/Shared/_Layout.cshtml
@{
    var bodyClass = string.Format(
        "{0}-{1}",
        ViewContext.RouteData.Values["controller"].ToString().ToLower(),
        ViewContext.RouteData.Values["action"].ToString().ToLower()
    );
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans" rel="stylesheet">
</head>
<body class="@bodyClass">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Shopping Lists", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("My Lists", "Index", "ShoppingLists")</li>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <div class="bottom-bar-spacer"></div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>